### ISSUE TITLE
Destroy throws error

### ISSUE THREAD

**Issue by ndvbd** [mar10/jquery-ui-contextmenu#138]
When I try to do destroy,

I get: Uncaught Error: cannot call methods on contextmenu prior to initialization; attempted to call method 'destroy'

**Comment by mar10** [comment]
`destroy()` is a standard method of the jQuery UI widget framework. You probably called this in a wrong way (read the docs there).

In order to process your issue, we need some more information, explanation what already was tried and/or concrete data.

A debuggable example (jsFiddle, Plunkr, CodePen, ...) may be helpful.

Please read the [Contribution Guidelines](https://github.com/mar10/fancytree/wiki/HowtoContribute#report-issues) for some hints on how to submit helpful feature requests and bug reports.

**Comment by ndvbd** [comment]
Thank you.
